version: '3'

services:
  app:
    build: ./
    volumes:
      - ./:/app
    container_name: schoolsystem-app
    ports:
      - "5000:5000"
    depends_on:
      - db
#      - cache
    links:
      - db
#      - cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-schoolsystem.cpkrcjihmbnz.us-east-1.rds.amazonaws.com:5432/schoolsystem
      - SPRING_DATASOURCE_USERNAME=schoolsystem
      - SPRING_DATASOURCE_PASSWORD=nguyendangkiet123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - REDIS_HOST=schoolsystem-redis-001.4nbd8h.0001.use1.cache.amazonaws.com
#      - REDIS_PORT=6379
    networks:
      - schoolsystem_network

  db:
    image: postgres:latest
    container_name: schoolsystem-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=schooladmin
      - POSTGRES_PASSWORD=nguyendangkiet123
    networks:
      - schoolsystem_network

#  cache:
#    image: redis:latest
#    container_name: schoolsystem-cache
#    ports:
#      - "6379:6379"
#    restart: always
#    networks:
#      - schoolsystem_network

networks:
  schoolsystem_network:
    driver: bridge
