server:
  port: 5000
version: ci-cd-v1.0
spring:
  application:
    name: pbl6-schoolsystem
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_PBL_HOST}:${DB_PBL_PORT}/${DB_PBL_NAME}
    username: ${DB_PBL_USER}
    password: ${DB_PBL_PASS}
    driver-class-name: org.postgresql.Driver
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  file:
    name: D:\kiet.nguyen-dang\project-base-learning-6\logs\elk-stack.log

sentry:
  dsn: https://dc6e336c168a4f549c3f2c385a7d2ed2@o4504355618291712.ingest.sentry.io/4504355624058880
  logging:
    minimum-breadcrumb-level: debug
    minimum-event-level: info
  in-app-includes: com.backend.pbl6schoolsystem
  send-default-pii: true
  exception-resolver-order: -1
  traces-sample-rate: 1.0